"use strict";

module.exports = {
    ROLE_ROOT: 'ROLE_ROOT',
    ROLE_ADMIN: 'ROLE_ADMIN',
    ROLE_MANAGER: 'ROLE_MANAGER',
    ROLE_CONTENT_MANAGER: 'ROLE_CONTENT_MANAGER',
    ROLE_ACCOUNTANT: 'ROLE_ACCOUNTANT',
    ROLE_CUSTOMER_MANAGER: 'ROLE_CUSTOMER_MANAGER',
    ROLE_LECTURER_MANAGER: 'ROLE_LECTURER_MANAGER',
    ROLE_STUDENT: 'ROLE_STUDENT',
    ROLE_LECTURER: 'ROLE_LECTURER', // Giảng viên.
};